[phases.setup]
nixPkgs = ["python310", "playwright", "python310Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install"]

[phases.start]
cmd = "python aviso_bot.py"
